config/routes.rb
Microblog::Application.routes.draw do
  
  root 'main#index'

  devise_for :users, controllers: { registrations: "registrations" }

  devise_scope :user do
    get 'login' => 'devise/sessions#new'
    get 'join' => 'devise/registrations#new'
    get 'settings' => 'devise/registrations#edit'
  end

  resources :users do
  	member do
  		get :subscribed, :subscribers
  	end
  end
  resources :relationships
  resources :posts

end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :title, presence: true
  validates :content, presence: true
  validates :content, length: { maximum: 140 }

  def self.from_users_subscribed_by(user)
    subscribed_user_ids = "SELECT subscribed_id FROM relationships
                         WHERE subscriber_id = :user_id"
    where("user_id IN (#{subscribed_user_ids}) OR user_id = :user_id",
          user_id: user.id)
  end

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base

  belongs_to :subscriber, class_name: "User"
  belongs_to :subscribed, class_name: "User"

  validates :subscriber_id, presence: true
  validates :subscribed_id, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader

  validates :username, uniqueness: { case_sensitive: false }

  validates_integrity_of  :avatar
  validates_processing_of :avatar

  has_many :posts
  has_many :relationships, foreign_key: "subscriber_id", dependent: :destroy
  has_many :subscribed_users, through: :relationships, source: :subscribed
  has_many :reverse_relationships, foreign_key: "subscribed_id", class_name: "Relationship", dependent: :destroy
  has_many :subscribers, through: :reverse_relationships, source: :subscriber

  def following?(other_user)
    relationships.find_by(subscribed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(subscribed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(subscribed_id: other_user.id).destroy!
  end

  def feed
    Post.from_users_subscribed_by(self)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
    @user ||= current_user
    @post = current_user.posts.build if user_signed_in?
    @feed_items = current_user.feed if user_signed_in?
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :authenticate_user!, only: [:new, :create]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Post created"
      redirect_to root_url
    else
      flash[:error] = "Post cannot be created"
      redirect_to root_url
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:warning] = "Post deleted"
    redirect_to root_url
  end

	private

    def post_params
      params.require(:post).permit(:title, :content)
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 
  before_filter :configure_permitted_parameters
 
  protected
 
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) do |u|
        u.permit(:username, :email, :password, :password_confirmation, :avatar, :avatar_cache)
      end
      devise_parameter_sanitizer.for(:account_update) do |u|
        u.permit(:username,
          :email, :password, :password_confirmation, :current_password, :avatar, :avatar_cache)
      end
    end
 
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  before_filter :authenticate_user!, only: [:create, :destroy]

  def create
    @user = User.find(params[:relationship][:subscribed_id])
    current_user.follow!(@user)
    redirect_to :back
  end

  def destroy
    @user = Relationship.find(params[:id]).subscribed
    current_user.unfollow!(@user)
    redirect_to :back
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @post = current_user.posts.build if signed_in?
    @posts = @user.posts
  end

  def subscribed
    @user = User.find(params[:id])
    @users = @user.subscribed_users
    render 'show_follow'
  end

  def subscribers
    @user = User.find(params[:id])
    @users = @user.subscribers
    render 'show_follow'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { size: 40 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    = render 'shared/head'
  %body
    = render 'shared/alerts'
    = render 'shared/header'
    .content
      = yield

app/views/main/index.html.haml
- if user_signed_in?
  .vertical-menu.vertical-menu-2
    = render 'shared/user_info'
    .medium-offset.bottom
    %h4 Create new post
    = render 'shared/post_form'
  .vertical-block.vertical-block-6
    %h3 Posts
    - unless @feed_items.empty?
      - @feed_items.each do |f|
        .meta.bold
          %p= f.title
        %p= f.content
        .meta.italic
          %p #{time_ago_in_words(f.created_at)} ago
          .meta.bold
            %p by #{link_to User.find(f.user_id).username, User.find(f.user_id)}
        .small-offset.bottom
    - else
      %p Posts not found
- else
  .central
    .large-offset.bottom
    %h1 Microblog
    .description Elementary blog.
    .small-offset.bottom
    = link_to "Sign in", login_path, class: 'button large rounded blue'

app/views/posts/index.html.haml
= @posts.each do |f|
  = f.title
  = f.content

app/views/posts/new.html.haml
= form_for @post do |f|
  = f.text_field :title
  = f.text_field :content
  = f.submit
  

app/views/posts/show.html.haml
= @post.title
= @post.content

app/views/shared/_alerts.html.haml
- if flash[:error]
  .alert.error.center= flash[:error]
- if flash[:success]
  .alert.success.center= flash[:success]
- if flash[:warning]
  .alert.warning.center= flash[:warning]
- if flash[:notice]
  .alert.notice.center= flash[:notice]

app/views/shared/_feed.html.haml
%h3 Posts
- unless @user.posts.count == 0
  .small-offset.bottom
  - @user.posts.each do |f|
    .meta.bold
      %p= f.title
    %p= f.content
    .meta.italic
      %p= f.created_at
    - if @user == current_user
      %p= link_to 'Delete', f, method: :delete, data: { confirm: "Are you sure?" }
    .small-offset.bottom
- else
  %p Posts not found

app/views/shared/_follow_form.html.haml
- if current_user.following?(@user)
  = form_for(current_user.relationships.find_by_subscribed_id(@user.id), html: { method: :delete }) do |f|
    = f.submit 'Unfollow', class: 'button medium rounded pink'
- else
  - unless @user == current_user
    = form_for(current_user.relationships.build(subscribed_id: @user.id)) do |f|
      = f.hidden_field :subscribed_id
      = f.submit 'Follow', class: 'button medium rounded blue'

app/views/shared/_head.html.haml
%title Microblog
= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
= javascript_include_tag "application", "data-turbolinks-track" => true
= csrf_meta_tags

app/views/shared/_header.html.haml
.menubar
  .content
    .left
      .navbar-element
        %h3= link_to "Microblog", root_path
    .right
      - if user_signed_in?
        .navbar-element= link_to "Settings", settings_path
        .navbar-element #{link_to "Log out", destroy_user_session_path, method: :delete}
      - else
        .navbar-element= link_to "Log in", login_path
        .navbar-element= link_to "Sign up", join_path

app/views/shared/_post_form.html.haml
= form_for @post do |f|
  = f.text_field :title, placeholder: 'Title', class: 'textform'
  .extrasmall-offset.bottom
  = f.text_area :content, placeholder: 'Post', class: 'textarea small medium'
  %p= f.submit 'Create', class: 'button medium rounded blue'

app/views/shared/_user_info.html.haml
- unless @user.avatar.to_s == ''
	%p= image_tag @user.avatar, size: '60x60'
- else
	%p= gravatar_for @user, size: 60
%h4= link_to @user.username, @user
%p= pluralize(@user.posts.count, 'post')
.meta.bold
	%p= link_to pluralize(@user.subscribed_users.count, 'following'), "/users/#{@user.id}/subscribed"
	%p= link_to pluralize(@user.subscribers.count, 'subscribers'), "/users/#{@user.id}/subscribers"

app/views/users/show.html.haml
.vertical-menu.vertical-menu-2
  = render 'shared/user_info'
  .small-offset.bottom
  = render 'shared/follow_form'
.vertical-block.vertical-block-6
  = render 'shared/feed'

app/views/users/show_follow.html.haml
%h3 Subscribers
.small-offset.bottom
- unless @user.subscribers.empty?
  - @user.subscribers.each do |f|
    %p= link_to f.username, f
    .extrasmall-offset.bottom
- else
  %span Subscribers not found
.medium-offset.bottom
%h3 Followings
.extrasmall-offset.bottom
- unless @user.subscribed_users.empty?
  - @user.subscribed_users.each do |f|
    %p= link_to f.username, f
    .extrasmall-offset.bottom
- else
  %span Followings not found